### PR TITLE
Add support for internationalization

### PR DESCRIPTION
**Pull request by jtojnar**
Later, I can provide Czech translation.

### CODE REVIEW

**Comment by sblask** [comment]
Thanks for this! Is there any kind of tooling available to extract strings into messages,json? I wouldn't want to miss anything should I add messages in the future. I also have other add-ons where this could come in handy. I could provide German translations. Do you know any good program that helps with translations?

**Comment by jtojnar** [comment]
The WebExtensions internationalization is a joke, there is not even support for pluralization so I doubt there are any extractors. I found https://github.com/oliviertassinari/i18n-extract which might be reused for JS but does not seem to support HTML.

The only good JS translation toolkit is [L20n](http://l20n.org/) but even that has virtually no [tooling support](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/l20n.html).

**Comment by sblask** [comment]
Alright, thanks for the info and doing this manually. I came up with this to at least check that I've got all the keys in the messages.json:

```
diff --unified <(grep --perl-regexp --only-matching --no-filename 'browser.i18n.getMessage\("\K([^"]+)|"__MSG_\K([^_]+)|data-i18n="\K([^"]+)' $(find . -not -path '*node_modules*' -name '*.js*' -o -not -path '*node_modules*' -name '*.html') 2>/dev/null | sort) <(jq --raw-output 'keys[]' _locales/en/messages.json)
```

**Comment by sblask** [comment]
I added German translations, it works like a charm. Thanks for enabling that! If you want to add translations too, I added a command to start Firefox in the German, you could just modify that for your language to be able to test your translations.

**Pull request merged**
